dataset_name: "finetune_data/processed_data/hf_bdnv2_dataset/train"
tokenizer_path: "./data/tokenizers/tokenizer_bpe_None_SAFE_500_0_0.1.json"
mol_type: "SAFE"
max_seq_length: 64
num_proc: 8
streaming: False
validation_set_names: ["finetune_data/processed_data/hf_bdnv2_dataset/validation"]